{{ define "projectB-service" }}

{{- range $i, $e := . }}
{{ if ne $i "global" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $i }}
spec:
  selector:
    app: {{ lower $i }}
  ports:
    - protocol: TCP
      port: {{ $e.port }}
      targetPort: {{ $e.port }}

{{ end }}
{{- end }}

{{ end }}


